#!/bin/bash
set -e 
VALIDATOR="python site-validate.py -v"

BASE="http://fizlesh.ru"
$VALIDATOR "$BASE"
$VALIDATOR "$BASE/?page=z01News"
$VALIDATOR "$BASE/?page=z024Official"
$VALIDATOR "$BASE/?page=z025AboutUs"
$VALIDATOR "$BASE/?page=z026Life"
$VALIDATOR "$BASE/?page=z03Education"
$VALIDATOR "$BASE/?page=z03Education/2006"
$VALIDATOR "$BASE/?page=z03Education/2007"
$VALIDATOR "$BASE/?page=z03Education/2008"
$VALIDATOR "$BASE/?page=z03Education/2009"
$VALIDATOR "$BASE/?page=z03Education/2010"
$VALIDATOR "$BASE/?page=z03Education/lectures2011"
$VALIDATOR "$BASE/?page=z03Education/lesh-practicum"
$VALIDATOR "$BASE/?page=z027Equipment"
$VALIDATOR "$BASE/?page=z027Equipment/cloth"
$VALIDATOR "$BASE/?page=z027Equipment/docs"
$VALIDATOR "$BASE/?page=z027Equipment/equip"
$VALIDATOR "$BASE/?page=z027Equipment/stuff"
$VALIDATOR "$BASE/?page=z027Equipment/stuff"
$VALIDATOR "$BASE/?page=z04Science"
$VALIDATOR "$BASE/?page=z060JoinUs"
$VALIDATOR "$BASE/?page=z065Photoalbum"
$VALIDATOR "$BASE/?page=z066Humor"
$VALIDATOR "$BASE/?page=z07Links"
$VALIDATOR "$BASE/?page=z08Contact"

