menu = [
            [
                "Home",
                False,
                "/public"
            ],
            [
                "List",
                True,
                [
                    [
                        "Home",
                        "/public"
                    ],
                    [
                        "Api",
                        "/api"
                    ],
                    [
                        "Admin",
                        "/admin"
                    ]
                ]
            ],
            [
                "List2",
                True,
                [
                    [
                        "Home",
                        "/public"
                    ],
                    [
                        "Api",
                        "/api"
                    ],
                    [
                        "Admin",
                        "/admin"
                    ]
                ]
            ]
        ]