#!/bin/bash -e

# VPS Backuper
# ------------
# Please DO NOT EDIT THIS FILE directly, these changes will be LOST
# when updating script from git repo.
# Instead, edit <git-repo-root>/tools/backuper/backup.sh and then deploy it
# to /srv/tools/backup.sh

backup_folder=/backup
status_file=/tmp/backup-status

rm -rf "$backup_folder"
mkdir -p "$backup_folder"

backup_db()
{
	echo "dumping database $1"
	ENC=utf8
	if ! [ -z "$3" ]; then
		ENC=$3
	fi
	mysqldump -ubackup -pnothing_to_backup --default-character-set=$ENC "$1" | gzip > "$2"
}

# add more folders here if you need
echo "Taring git..."
tar czf "$backup_folder/git.tgz"  /srv/git
echo "Taring trac..."
tar czf "$backup_folder/trac.tgz" /srv/trac
echo "Taring etc..."
tar czf "$backup_folder/etc.tgz"  /etc
backup_db smf "$backup_folder/forum.sql.gz"
backup_db information_schema "$backup_folder/information_schema.sql.gz"
backup_db mysql "$backup_folder/mysql.sql.gz"
backup_db postfix "$backup_folder/postfix.sql.gz" "latin1"

echo "Taring attachments..."
tar czf "$backup_folder/attach.tgz"  /srv/www/clones/forum/attachments

plan_a()
{
    dest_host=doctor@doctor.dtdns.net
    rsync -avz "$backup_folder" "$dest_host:/data/backup/lesh/$back_date/"
}

plan_b()
{
    dest_host=mvel@mvel.dtdns.net
    chown -R mvel:mvel $backup_folder
    # reverse scp-ing works!
    dest_folder=backup/lesh/$back_date/
    ssh $dest_host mkdir -p $dest_folder
    # reverse scp-ying works!
    ssh $dest_host scp fizlesh.ru:$backup_folder/* $dest_folder
}

back_date="`date +%Y-%m-%d`"

if plan_a ; then
    echo "Backing to primary host $dest_host succeeded" 1>&2
    echo "OK" > $status_file
    exit 0
else
    echo "Backing to primary host $dest_host failed" 1>&2
fi

if plan_b ; then
    echo "Backing to secondary host $dest_host succeeded" 1>&2
    echo "OK" > $status_file
    exit 0
else
    echo "Backing to secondary host $dest_host failed" 1>&2
fi
