#!/bin/bash

# VPS Backup Invoker
# ------------------
# Please do not edit this file directly, get a copy from git
# tools/backup/backup-script.sh

status_file=/tmp/backup-status
letter_file=/tmp/backup-letter.txt
out_log=/tmp/backup-letter.log
err_log=/tmp/backup-letter.err
# mailx on Debian cannot send letters with attachments, so we use mutt
mail_cmd=mutt

mailto="vdm-photo@ya.ru,dichlofos-mv@yandex.ru,trousev@yandex.ru,trousev.archive@gmail.com"

# clear garbage
rm -f $status_file
rm -f $out_log $out_log.gz
rm -f $err_log $err_log.gz

echo -en "A backup report for dev.fizlesh.ru\\n---------------------------------------\\n" > $letter_file
/srv/tools/backup.sh 1> $out_log 2> $err_log
echo -en "A tail of the error messages (last 20 lines):\\n\\n" >> $letter_file
tail -n 20 $err_log >> $letter_file
gzip $out_log
gzip $err_log

STATUS=$(cat /tmp/backup-status)
if [ $STATUS. == "OK." ]; then
    #$mail_cmd -a $out_log.gz $err_log.gz -s "[lesh-dev] Backup OK" -- $mailto < $letter_file
    echo "No need to send mail"
else
    $mail_cmd -a $out_log.gz -a $err_log.gz -s "[lesh-dev] BACKUP FAILURE" -- "$mailto" < $letter_file
fi
