---
- hosts: build
  tasks:
  - name: install system-wide python packages
    apt:
      package: "{{ packages }}"
      state: present
    vars:
      packages:
      - python3-pip
      - python3-virtualenv
    become: yes
  - name: clone lesh-dev repository
    git:
      dest: ~/lesh-dev
      repo: https://github.com/lesh-dev/core.git
  - name: install python dependencies
    # Есть модуль pip, но у него не получилось разобраться в версиях питона и virtualenv.
    # Поэтому просто шелл.
    # В норме билд вообще делается не на той машине, на которой запускается сервер,
    # а приложения надо паковать во что-нибудь удобное.
    # То же касается и npm.
    shell: >-
      export LC_ALL=en_US.UTF-8;
      /usr/bin/python3 -m virtualenv -p /usr/bin/python3 venv;
      . venv/bin/activate;
      pip3 install -r requirements.txt
    args:
      chdir: ~/lesh-dev/site/yasm
  - name: copy database
    copy:
      src: ~/lesh-dev/site/yasm/fizlesh.sqlite3
      dest: ~/lesh-dev/site/yasm/fizlesh.sqlite3
  - name: download nodejs
    get_url:
      url: https://nodejs.org/dist/v8.11.4/node-v8.11.4-linux-x64.tar.xz
      dest: ~/Nodejs.tar.xz
    tags: npm
  - name: unpack nodejs
    unarchive:
      src: ~/Nodejs.tar.xz
      dest: ~/
      remote_src: yes
    tags: npm
  - name: npm install
    shell: PATH=$PATH:~/node-v8.11.4-linux-x64/bin npm install
    args:
      chdir: ~/lesh-dev/site/yasm/instance/ui
    tags: npm
  - name: npm run build
    shell: PATH=$PATH:~/node-v8.11.4-linux-x64/bin npm run build
    args:
      chdir: ~/lesh-dev/site/yasm/instance/ui
    tags: npm