"""

"""

from instance import create
from instance.autogen.generate import main as proto_gen
from flask_script import Manager
import shutil
import os
import subprocess

application = create()


def main():
    manager = Manager(application)

    @manager.command
    def generate():
        """generate base classes/interfaces/handlers from proto-scheme"""
        proto_gen()

    @manager.command
    def docs():
        """generate documentation"""
        base_cwd = os.getcwd()
        RUN_PATH = os.path.dirname(os.path.abspath(__file__))
        DOC_ROOT = os.path.join(RUN_PATH, 'docs')
        os.chdir(DOC_ROOT)
        shutil.rmtree('source/autogenerated')
        subprocess.check_call(['sh', 'build_docs.sh'])
        subprocess.check_call(['sh', 'build_docs.sh'])
        os.chdir(base_cwd)
    manager.run()


if __name__ == '__main__':
    main()
