"""

"""

from instance import create, initialize
from instance.autogen.generate import main as proto_gen
from flask_script import Manager
import shutil
import os
import subprocess


def main():
    manager = Manager(create())

    @manager.command
    def generate():
        """generate base classes/interfaces/handlers from proto-scheme"""
        proto_gen()

    @manager.command
    def docs():
        """generate documentation"""
        base_cwd = os.getcwd()
        RUN_PATH = os.path.dirname(os.path.abspath(__file__))
        DOC_ROOT = os.path.join(RUN_PATH, 'docs')
        os.chdir(DOC_ROOT)
        shutil.rmtree('source/autogenerated', ignore_errors=True)
        subprocess.check_call(['sh', 'build_docs.sh'])
        subprocess.check_call(['sh', 'build_docs.sh'])
        os.chdir(base_cwd)

    @manager.command
    def runserver():
        """run development server"""
        initialize()
        manager.app.run()
    manager.run()


if __name__ == '__main__':
    main()
